name: Build and Deploy

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'src/**'
    branches: [ main ]

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --configuration Release --no-restore
       
      #- name: Test
      #  run: dotnet test ./src --configuration Release --no-build --verbosity normal
      
      - name: Pack
        run: dotnet pack ./src/Nager.Immich/Nager.Immich.csproj --configuration Release --no-restore --no-build --output ./out

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ./out/*.nupkg

  push:
    runs-on: ubuntu-latest
    needs: build-and-pack
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ./out

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Push NuGet package
        run: |
          dotnet nuget push $GITHUB_WORKSPACE/out/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --skip-duplicate